Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

   config.vm.define "m3" do |m3|
	 m3.vm.hostname  = "dockerserver1"
	 m3.vm.network "private_network", ip: "172.30.18.148"
	 m3.vm.provider "virtualbox" do |vb|
	   vb.name = "dockerserver1"
	 end
	 config.vm.provision "shell",path:"docker.sh"
  end
end